#!/bin/bash
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

tput setaf 3;
echo "################################################################"
echo "Install Nix Packages ..."
echo "################################################################"
echo;tput sgr0

#Install Packages
nix-env -iA nixpkgs.caffeine-ng &&
nix-env -iA nixpkgs.ventoy-bin-full &&
nix-env -iA nixpkgs.hardinfo

#Copy Desktop Files
sudo cp -rf nix-desktop-files/* ~/.nix-profile/share/applications/

#Create Symbolic links for Desktop Files
sudo ln -s ~/.nix-profile/share/applications/* /usr/share/applications/



tput setaf 11;
echo "################################################################"
echo "Nix Packages has been installed"
echo "################################################################"
echo;tput sgr0

