#!/bin/bash
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

config_dir=/etc/dnf/

tput setaf 3;
echo "################################################################"
echo "Backup and Update DNF config file ..."
echo "################################################################"
echo;tput sgr0

#Backup orginal dnf config file
cd $config_dir
sudo cp dnf.conf dnf.conf.bak
echo "Backup Complete."
echo " "

cd -

#Copy & replace file dnf config file
sudo cp -if  dnf.conf $config_dir
echo " "
echo "done."

###############################################################################
echo "DNF PACKAGES UPDATE ..."
###############################################################################

sudo dnf update -y

tput setaf 2;
echo "################################################################"
echo "DNF Packages has been Updated"
echo "################################################################"
echo;tput sgr0





